# Generated by Django 2.0.7 on 2019-09-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=10)),
                ('dif', models.CharField(max_length=10)),
                ('que', models.TextField()),
                ('ch1', models.CharField(max_length=10)),
                ('ch2', models.CharField(max_length=10)),
                ('ch3', models.CharField(max_length=10)),
                ('ch4', models.CharField(max_length=10)),
                ('ans', models.CharField(max_length=2)),
                ('wor', models.TextField()),
                ('valid', models.BooleanField()),
                ('vaby', models.CharField(max_length=10)),
            ],
        ),
    ]
