# Generated by Django 2.2.7 on 2019-11-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maths',
            name='que',
            field=models.TextField(max_length=5120),
        ),
    ]
